config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, GeneratePasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email.confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password.recovery/', GeneratePasswordView.as_view(), name='recovery_pass'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email адрес')
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=15, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='Страна', **NULLABLE)

    token = models.CharField(max_length=100, verbose_name='Токен', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from catalog.forms import StyleMixin
from users.models import User


class UserRegisterForm(StyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)

users/views.py
import secrets

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from users.forms import UserRegisterForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = self.request.buid_absolute_uri(reverse('users:email-confirm', args=(user.token,)))
        # url = f'http://{host}/users/email.confirm/{token}'
        send_mail(
            subject='Подтверждение почты',
            message=f'Для подтверждения почты перейдите по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class GeneratePasswordView(PasswordResetView):
    form_class = PasswordResetForm
    template_name = 'users/reset_password.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):

        user = User.objects.filter(email=form.cleaned_data['email']).first()
        if user:
            new_password = User.objects.make_random_password()
            user.set_password(new_password)
            user.save()
        user.email_user(
            subject='Смена пароля',
            message=f'Ваш новый пароль: {new_password}',
        )
        return redirect(reverse('users:login'))

        # email = form.cleaned_data['email']
        # user = User.objects.get(email=email)
        # if user:
        #     password = secrets.token_hex(10)
        #     user.set_password(password)
        #     user.save()
        # send_mail(
        #     subject='Смена пароля',
        #     message=f'Ваш новый пароль: {password}',
        #     from_email=EMAIL_HOST_USER,
        #     recipient_list=[user.email]
        # )
        # return redirect(reverse('users:login'))


# def recovery_pass(request):
#     chars = '+-/*!&$#?=@<>abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
#     new_password = ''
#     for i in range(10):
#         new_password += random.choice(chars)
#
#     if request.method == 'POST':
#         email = request.POST.get('email')
#         user = get_object_or_404(User, email=email)
#         password = new_password
#         user.set_password(password)
#         user.save()
#         send_mail(
#             subject='Восстановление пароля',
#             message=f'Сгенерирован новый пароль: {user.password}',
#             from_email=EMAIL_HOST_USER,
#             recipient_list=[user.email]
#         )
#         return redirect(reverse('users:login'))
#     return render(request, 'users/reset_password.html')

users/templates/users/login.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="row">
                <!--enctype="multipart/form-data" необходимо прописывать чтобы была возможность загружать не только текст но и файлы>-->
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Войти
                            </button>
                            <a type="submit" class="btn btn-primary" href="{% url 'users:recovery_pass'%}" >
                                Восстановить пароль
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="row">
                <!--enctype="multipart/form-data" необходимо прописывать чтобы была возможность загружать не только текст но и файлы>-->
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Сгенерировать новый пароль
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="row">
                <!--enctype="multipart/form-data" необходимо прописывать чтобы была возможность загружать не только текст но и файлы>-->
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}