catalog/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ContactsView, ProductListView, ProductDetailView, BlogCreateView, BlogListView, \
    BlogDetailView, BlogUpdateView, BlogDeleteView, ProductCreateView, ProductUpdateView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/edit/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/view/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, GeneratePasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email.confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password.recovery/', GeneratePasswordView.as_view(), name='recovery_pass'),
]

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    picture = models.ImageField(upload_to='catalog/picture', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='Категория', **NULLABLE,
                                 related_name='product')
    price = models.IntegerField(verbose_name='Цена')
    created_at = models.DateField(auto_now=True, verbose_name='Дата создания')
    updated_at = models.DateField(auto_now=True, verbose_name='Дата изменения')
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='Опубликован')

    def __str__(self):
        return f'{self.name} - {self.category}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name', 'price')
        permissions = [
            ('can_edit_published', 'Can edit is_published'),
            ('can_edit_description', 'Can edit description'),
            ('can_edit_category', 'Can edit category'),
        ]


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    picture = models.ImageField(upload_to='catalog/blog/picture', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateField(auto_now=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликованно')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('title', 'content')


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version = models.FloatField(max_length=10, verbose_name='Версия')
    name_version = models.CharField(max_length=100, verbose_name='Название версии', **NULLABLE)
    sign_version = models.BooleanField(default=True, verbose_name='Активна')

    def __str__(self):
        return f'{self.version}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django.forms import ModelForm, forms, BooleanField

from catalog.models import Product, Version

valid_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

class StyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleMixin, ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'category', 'picture')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        for word in valid_words:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError('Запрещенный продукт')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        for word in valid_words:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError('Запрещенный продукт')
        return cleaned_data


class VersionForm(StyleMixin, ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class ProductModeratorForm(StyleMixin, ModelForm):
    class Meta:
        model = Product
        fields = ('is_published', 'description', 'category',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.http import request
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify
from django.core.mail import send_mail

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Blog, Version, Category
from catalog.services import get_category_from_cache, get_product_from_cache


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form: ProductForm):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    # def form_valid(self, form):
    #     product = form.save()
    #     user = self.request.user
    #     product.owner = user
    #     product.save()
    #     return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if formset.is_valid:
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user

        if user == self.object.owner:
            return ProductForm
        if user.has_perm('catalog.can_edit_published') and user.has_perm(
            'catalog.can_edit_description') and user.has_perm('catalog.can_edit_category'):
            return ProductModeratorForm
        raise PermissionDenied

# def product_list(request):
#     products = Product.objects.all()
#     context = {
#         "products": products
#     }
#     return render(request, 'products_list.html', context)

class ProductListView(ListView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = get_product_from_cache()
        for product in products:
            version = Version.objects.filter(product=product)
            active_version = version.filter(sign_version=True)
            if active_version:
                product.active_version = active_version.last().version
            else:
                product.active_version = 'Нет активной версии'
        context_data['object_list'] = products
        return context_data


# def contacts(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         phone = request.POST.get('phone')
#         message = request.POST.get('message')
#         print(f'{name}, контактный телефон: {phone}\nСообщение: {message}')
#     return render(request, 'contacts.html')

class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

    def post(self, request):
        if self.request.method == 'POST':
            name = self.request.POST.get('name')
            phone = request.POST.get('phone')
            message = request.POST.get('message')
            print(f'{name}, контактный телефон: {phone}\nСообщение: {message}')
        return render(request, 'catalog/contacts.html')


# def product_detail(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     context = {
#         "product": product
#     }
#     return render(request, 'product_detail.html', context)


class ProductDetailView(DetailView):
    model = Product


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        """выводит только опубликованные блоги"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'picture')
    success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """Cчетчик просмотров блога"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'picture')

    # success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_category_from_cache()
        return context_data

    # def get_queryset(self):
    #     return get_category_from_cache()

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="row">
    <div class="coll-12">
        <div class="coll-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{object.title}}"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'catalog:blog_list' %}" class="btn btn-warning"> Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <img class="card-img-top" src="/media/{{ object.picture }}">
            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ object.content }}</li>
            </ul>
            <a class="btn btn-primary" href="{% url 'catalog:blog_list'%}" role="button">Назад</a>
        </div>
        <div class="card-footer">
            Просмотры {{object.views_count}}
        </div>
    </div>
</div>
</div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif%}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="coll-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:blog_create' %}">Добавить блог</a>
</div>
{% for object in object_list %}
<div class="col">
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">
                {{object| title}}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-primary" href="{% url 'catalog:blog_detail' object.pk %}" role="button">Посмотреть</a>
                    <a class="btn btn-outline-primary" href="{% url 'catalog:blog_update' object.pk %}" role="button">Изменить</a>
                    <a class="btn btn-outline-primary" href="{% url 'catalog:blog_delete' object.pk %}" role="button">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}
{% endblock %}

<!--href="{% url 'materials:view' object.pk %}"-->
<!--href="{% url 'materials:edit' object.pk %}"-->
<!--href="{% url 'materials:delete' object.pk %}"-->

catalog/templates/catalog/category_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}

{% block content %}
{% if user.is_authenticated %}
<div class="coll-12 mb-5">
    <a class="btn btn-outline-primary">Добавить категорию</a>
</div>
{% endif %}
{% for category in category_list %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <img class="card-img-top" src="{{ category.picture | media_filter }}">
            <h4 class="my-0 font-weight-normal">{{ category.name }}</h4>
            <h4 class="my-0 font-weight-normal">{{ category.description }}</h4>

        </div>
        <div class="card-body">

            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ category.description }}</li>
            </ul>
            <div class="btn-group">

                <a class="btn btn-primary" role="button">Посмотреть</a>
            </div>

        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    {% include 'catalog/includes/inc_menu_1.html' %}
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Текст" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            {% include 'catalog/includes/inc_menu_2.html' %}

        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% load static %}
{% load my_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    {% include 'catalog/includes/inc_menu_1.html' %}
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
</div>

<div class="container">
    <div class="row text-center">
{% block content %}

{% endblock %}
    </div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
{% include 'catalog/includes/inc_menu_2.html' %}
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <img class="card-img-top" src="{{ product.picture | media_filter }}">
            <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ object.price }} р.</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ object.category }}</li>
                <li>{{ object.description|slice:100 }}</li>
            </ul>
            <a class="btn btn-primary" href="{% url 'catalog:product_list'%}" role="button">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="row">
                <!--enctype="multipart/form-data" необходимо прописывать чтобы была возможность загружать не только текст но и файлы>-->
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                {% if object %}
                                Редактирование продукта
                                {% else %}
                                Создание продукта
                                {% endif%}
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </div>
                {% if object %}
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                            <hr>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}

{% block content %}
{% if user.is_authenticated %}
<div class="coll-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
</div>
{% endif %}
{% for product in object_list %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <img class="card-img-top" src="{{ product.picture | media_filter }}">
            <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
            <h8 class="my-0 font-weight-normal">Версия: {{ product.active_version }}</h8>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ product.price }} р.</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ product.category }}</li>
                <li>{{ product.description|slice:100 }}</li>
            </ul>
            <div class="btn-group">
                <a class="btn btn-primary" role="button">Купить</a>
                <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}"
                   role="button">Посмотреть</a>
                {% if user.is_authenticated and perms.catalog.can_edit_published and perms.catalog.can_edit_description and perms.catalog.can_edit_description or user == product.owner %}
                <a class="btn btn-primary" href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endfor %}

{% endblock %}